### ISSUE TITLE
Can you fix the link?

### ISSUE THREAD

**Issue by syzlhh** [Boyiliee/RESIDE-dataset-link#1]
（Dropbox）： http://tinyurl.com/y98eo4w8  

（Baidu Yun）：http://tinyurl.com/yaohd3yv     Passward:  g0s6
It's not the baidu Yun link.Can you fix this link. Thanks very much.

**Comment by java-abhinav07** [comment]
Even the Dropbox link for OTS isn't redirecting, if possible kindly fix that too @Boyiliee

**Comment by Boyiliee** [comment]
> （Dropbox）： http://tinyurl.com/y98eo4w8
> 
> （Baidu Yun）：http://tinyurl.com/yaohd3yv Passward: g0s6
> It's not the baidu Yun link.Can you fix this link. Thanks very much.

Thanks for your question. This is the short version of Baidu Link. It still works for me now. If it doesn't work for you, please try: https://pan.baidu.com/share/init?surl=iw3Un_Y9iSbhPFPZJHTSoA. 

Hope this helps.

Boyi

**Comment by Boyiliee** [comment]
> Even the Dropbox link for OTS isn't redirecting, if possible kindly fix that too @Boyiliee

Thanks for your interest in RESIDE. The link still works for me. Please try https://www.dropbox.com/sh/0du2dhd6hy085ms/AAA7qHcIvCzU7tsRwur9MAB0a?dl=0. 

Hope this helps. 

Boyi
