### ISSUE TITLE
ITS数据集链接问题

### ISSUE THREAD

**Issue by djjandXMU** [Boyiliee/RESIDE-dataset-link#2]
请问下能否提供ITS数据库的百度网盘链接，文档里的貌似写错了，辛苦了。

**Comment by Boyiliee** [comment]
Hi, @djjandXMU ,

Thanks for your question. I've checked it and it works very well for me: （Baidu Yun）：http://tinyurl.com/yaohd3yv     Passward:  g0s6. Please follow the instruction carefully.

Note: For Baidu Yun Link, you might need to refresh again or copy the link to a new webpage if it fails to redirect.

Hope this helps.

Best,
Boyi
