### ISSUE TITLE
Updated OTS dataset link

### ISSUE THREAD

**Issue by PinJui** [Boyiliee/RESIDE-dataset-link#3]
Hi, thank you for the great work.
I had downloaded the OTS dataset with the updated link
https://bit.ly/3sDuD0R
but after I extract the file, there are over 300000 images and I couldn't find the ground truth inside.
Can you please help me where to find the ground truth images or where can I download the beta version that consists only 72135 images

thank you very much !

**Comment by veb-101** [comment]
Hello, @PinJui @Boyiliee was wondering the same, isn't there supposed to be a clear and hazy images folder? Am I missing something? If so can you please tell me?

**Comment by Boyiliee** [comment]
Hi, @PinJui and @veb-101, thanks for your questions. 

We are fixing the dropbox now.  I've checked Baidu link, it works very well. Please copy and paste the link to your browser and download the dataset: （Baidu Yun）:   https://pan.baidu.com/s/1YMYUp5P6FpX_5b7emjgrvA   Passward:  w54h.

Hope this helps.

Best,
Boyi
